spring:
  profiles: default
server:
  port: 8062
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  profiles: docker
  zipkin:
    baseUrl: http://tracing-server:9411
server:
  port: 8062
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
