ota:
  cache:
    ttl: 60
    heap-size: 100

---
spring:
  profiles: default
server:
  port: 8061
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  profiles: docker
  zipkin:
    baseUrl: http://tracing-server:9411
server:
  port: 8061
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
