zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    ota-service: /otaservice/**
    logser-service: /logser/**
feign:
  hystrix:
    enabled: true

server:
  port: 8094
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

# Internationalization
spring.messages.basename: messages/messages

---
spring:
  profiles: docker
  zipkin:
    baseUrl: http://tracing-server:9411
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://hadoop01:8761/eureka/
